# Generated by Django 5.1.7 on 2025-03-24 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AreaPreparacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        choices=[("cocina", "Cocina"), ("bar", "Bar")],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Área de Preparación",
                "verbose_name_plural": "Áreas de Preparación",
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre de la categoría", max_length=50, unique=True
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, help_text="Descripción de la categoría", null=True
                    ),
                ),
                (
                    "area_preparacion",
                    models.ForeignKey(
                        help_text="Área donde se prepara esta categoría de productos",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.areapreparacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(help_text="Nombre del producto", max_length=100),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, help_text="Precio del producto", max_digits=10
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, help_text="Descripción del producto", null=True
                    ),
                ),
                (
                    "esta_disponible",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el producto está disponible para venta",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen del producto",
                        null=True,
                        upload_to="productos/",
                    ),
                ),
                (
                    "tiempo_preparacion",
                    models.IntegerField(
                        default=15, help_text="Tiempo de preparación en minutos"
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        help_text="Categoría del producto",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["categoria", "nombre"],
            },
        ),
    ]
