# Generated by Django 5.1.7 on 2025-03-24 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="detallepedido",
            name="preparado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items_preparados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="detallepedido",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="products.producto"
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="cajero",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pedidos_cobrados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="mesa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="orders.mesa"
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="mesero",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pedidos_tomados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="detallepedido",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="orders.pedido",
            ),
        ),
    ]
