# Generated by Django 5.1.7 on 2025-03-31 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("tarjeta", "Tarjeta de crédito/débito"),
                            ("transferencia", "Transferencia bancaria"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="orders.pedido",
                    ),
                ),
            ],
        ),
    ]
