# Generated by Django 5.1.7 on 2025-03-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_pago"),
    ]

    operations = [
        migrations.AddField(
            model_name="pago",
            name="cambio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="pago",
            name="monto_recibido",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
