# Generated by Django 5.1.7 on 2025-04-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_pago_cambio_pago_monto_recibido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pago",
            name="metodo",
            field=models.CharField(
                choices=[
                    ("efectivo", "Efectivo"),
                    ("tarjeta", "Tarjeta de crédito/débito"),
                ],
                max_length=20,
            ),
        ),
    ]
