# Generated by Django 5.1.7 on 2025-04-29 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_alter_pago_metodo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pago",
            name="metodo",
            field=models.CharField(
                choices=[
                    ("efectivo", "Efectivo"),
                    ("pendiente", "Pendiente"),
                    ("tarjeta", "Tarjeta de crédito/débito"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PagoPendiente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cliente_nombre", models.CharField(max_length=255)),
                ("fecha_promesa", models.DateField()),
                ("esta_pagado", models.BooleanField(default=False)),
                ("fecha_pago_real", models.DateField(blank=True, null=True)),
                ("notas_adicionales", models.TextField(blank=True, null=True)),
                (
                    "pago",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pendiente_info",
                        to="orders.pago",
                    ),
                ),
            ],
        ),
    ]
