# Generated by Django 5.1.7 on 2025-04-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_alter_pago_metodo_pagopendiente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="estado_pago",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("pagado", "Pagado"),
                    ("impago", "Impago"),
                    ("cancelado", "Cancelado"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
    ]
